

name: Daily Run 2

on:
  schedule:
    - cron: "2 0 * * *"
  
  push:
    branches: [ master ]

jobs:
  check_date:
    runs-on: ubuntu-latest
    name: Check latest commit
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - uses: actions/checkout@v2
      - name: Print latest_commit
        run: echo ${{ github.sha }}

      - id: should_run
        continue-on-error: true
        name: check latest commit is less than a day
        if: ${{ github.event_name == 'schedule' }}
        run: test -z $(git rev-list  --after="24 hours"  ${{ github.sha }}) && echo "::set-output name=should_run::false"

  run_tests:
    runs-on: ubuntu-latest
    name: Run Tests
    needs: check_date
    if: ${{ needs.check_date.outputs.should_run != 'false' }}

    steps:
      - uses: actions/checkout@v3
  
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: 3.10

      - run: python manage.py test
        